services:
  db:
    image: postgres:16-alpine
    container_name: greendrop-db
    environment:
      POSTGRES_DB: greendrop
      POSTGRES_USER: greendrop
      POSTGRES_PASSWORD: greendrop
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U greendrop -d greendrop"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: greendrop-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgres://greendrop:greendrop@db:5432/greendrop
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  db_data:
